# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a370d7081b7188e2843943f275138d9bc6c5803b300a61665acf22a3a2e7e3f1ead21fd30e181b38a019e3a30092c30123fd580f4882ecab4cbc0a425337b83

test:
  secret_key_base: d8ec470c37657960dd86d9342d1aabaa072b74da831cc8c29ce3392e8e00a9335b38a09c21b0d9a8131ce60556ea55fb71185e08dd4c6c2c6536e9e5c03f294b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
